# Generated by Django 5.1.7 on 2025-03-28 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crafting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('probability', models.FloatField()),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ObjectCategorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('objectCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valApp.objectcategorys')),
                ('objectType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valApp.objecttypes')),
            ],
        ),
        migrations.CreateModel(
            name='craftingRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('craft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valApp.crafting')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valApp.objects')),
            ],
        ),
        migrations.AddField(
            model_name='crafting',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valApp.objects'),
        ),
        migrations.AddField(
            model_name='crafting',
            name='proffesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valApp.professions'),
        ),
    ]
