# Generated by Django 5.1.7 on 2025-03-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='objects/images/'),
        ),
    ]
