# Generated by Django 5.1.7 on 2025-03-28 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valApp', '0003_professions_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroeTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Races',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='races/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Rarities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RolesCombatUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('supply', models.IntegerField()),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='heroes/images/')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valApp.heroetypes')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valApp.races')),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valApp.rarities')),
            ],
        ),
        migrations.CreateModel(
            name='CombatUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('supply', models.IntegerField()),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('troopPoints', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='combatUnits/images/')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valApp.races')),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valApp.rarities')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valApp.rolescombatunits')),
            ],
        ),
    ]
