# Generated by Django 5.1.7 on 2025-03-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valApp', '0004_heroetypes_races_rarities_rolescombatunits_heroes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroeRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='combatunits',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='objects/images/'),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='objects/images/'),
        ),
        migrations.AlterField(
            model_name='professions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='objects/images/'),
        ),
        migrations.AlterField(
            model_name='races',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='objects/images/'),
        ),
    ]
