# Generated by Django 5.1.7 on 2025-03-31 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valApp', '0005_mensaje_alter_combatunits_image_alter_heroes_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
