# Generated by Django 5.1.7 on 2025-03-29 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valApp', '0005_heroeroles_alter_combatunits_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroes',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='valApp.heroeroles'),
            preserve_default=False,
        ),
    ]
