# Generated by Django 5.1.7 on 2025-03-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valApp', '0006_heroes_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combatunits',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='objects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='professions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='races',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
