# Generated by Django 5.1.7 on 2025-03-31 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valApp', '0006_delete_mensaje'),
        ('valApp', '0007_alter_combatunits_image_alter_heroes_image_and_more'),
    ]

    operations = [
    ]
