# Generated by Django 5.1.7 on 2025-04-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valApp', '0009_objects_mint_alter_combatunits_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objects',
            name='uri',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
