# Generated by Django 5.1.7 on 2025-04-04 10:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valApp', '0010_objects_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objects',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
