# Generated by Django 5.1.7 on 2025-04-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valApp', '0012_objects_nftimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='objects',
            name='supply',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='objects',
            name='nftImage',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
