# Generated by Django 5.1.7 on 2025-04-07 11:45

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valApp', '0013_objects_supply_alter_objects_nftimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetsTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('supply', models.IntegerField()),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valApp.rarities')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valApp.petstypes')),
            ],
        ),
    ]
