# Generated by Django 5.1.7 on 2025-04-10 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valApp', '0014_petstypes_pets'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectsPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('amount', models.IntegerField()),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valApp.objects')),
            ],
        ),
    ]
