# Generated by Django 5.1.7 on 2025-04-11 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valApp', '0016_objectsprices_created_at_guilds_guildmembers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guildmembers',
            old_name='kkey',
            new_name='roleuuid',
        ),
        migrations.AddField(
            model_name='guildmembers',
            name='avatar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='guildmembers',
            name='herokind',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='guildmembers',
            name='idRank',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='guildmembers',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='valApp.professions'),
        ),
        migrations.AddField(
            model_name='guildmembers',
            name='professionMastery',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='guildmembers',
            name='ranking',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='guildmembers',
            name='usdc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guildmembers',
            name='uuid',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guildmembers',
            name='weeklyCrafts',
            field=models.IntegerField(null=True),
        ),
    ]
