# Generated by Django 5.1.7 on 2025-04-11 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valApp', '0017_rename_kkey_guildmembers_roleuuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guildmembers',
            old_name='idGuild',
            new_name='guild',
        ),
        migrations.AddField(
            model_name='guildmembers',
            name='heroLvl',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='guildmembers',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='valApp.races'),
        ),
    ]
