# Generated by Django 5.1.7 on 2025-04-11 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valApp', '0018_rename_idguild_guildmembers_guild_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildmembers',
            name='guild',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='valApp.guilds'),
        ),
    ]
