# Generated by Django 5.1.7 on 2025-04-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valApp', '0019_alter_guildmembers_guild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildmembers',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='guildmembers',
            name='alchemist',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guildmembers',
            name='architect',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guildmembers',
            name='artisan',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guildmembers',
            name='blacksmith',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guildmembers',
            name='engineer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guildmembers',
            name='explorer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guildmembers',
            name='jeweler',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guildmembers',
            name='miner',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guildmembers',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guildmembers',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guildmembers',
            name='roleuuid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guildmembers',
            name='uuid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guildmembers',
            name='uuidGuild',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
