# Generated by Django 5.1.7 on 2025-04-11 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valApp', '0021_alter_guildmembers_herolvl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectsBuyPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valApp.objects')),
            ],
        ),
    ]
