# Generated by Django 5.1.7 on 2025-04-11 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valApp', '0022_objectsbuyprices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildmembers',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='valApp.professions'),
        ),
        migrations.AlterField(
            model_name='guildmembers',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='valApp.races'),
        ),
    ]
