# Generated by Django 5.1.7 on 2025-04-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valApp', '0025_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
