# Generated by Django 5.1.7 on 2025-04-13 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valApp', '0026_usernotification_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='upodated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
