# Generated by Django 5.1.7 on 2025-04-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valApp', '0027_usernotification_upodated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotification',
            name='upodated_at',
        ),
        migrations.AddField(
            model_name='usernotification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
