# Generated by Django 5.1.7 on 2025-04-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valApp', '0029_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='wallet',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
