# Generated by Django 5.1.7 on 2025-04-14 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valApp', '0031_profileuser_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsprices',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectsprices_set', to='valApp.objects'),
        ),
    ]
