# Generated by Django 5.1.7 on 2025-04-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valApp', '0032_alter_objectsprices_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatunits',
            name='mint',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='combatunits',
            name='nftImage',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='combatunits',
            name='uri',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='heroes',
            name='mint',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='heroes',
            name='nftImage',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='heroes',
            name='uri',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
