# Generated by Django 5.1.7 on 2025-04-19 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valApp', '0033_combatunits_mint_combatunits_nftimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftingrequirements',
            name='craft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='valApp.crafting'),
        ),
    ]
