# Generated by Django 5.1.7 on 2025-04-20 08:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valApp', '0034_alter_craftingrequirements_craft'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroes',
            name='animation',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AddField(
            model_name='objects',
            name='animation',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
