# Generated by Django 5.1.7 on 2025-04-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valApp', '0035_heroes_animation_objects_animation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objects',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
