# Generated by Django 5.1.7 on 2025-04-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valApp', '0036_alter_objects_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectsprices',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
