# Generated by Django 5.1.7 on 2025-04-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valApp', '0037_objectsprices_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectsbuyprices',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
